[build]
  command = "cd client && npm install && npm run build"
  publish = "client/build"

[functions]
  directory = "server/api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/socket/:splat"  
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
